### ISSUE TITLE
ROS2 interface

### ISSUE THREAD

**Issue by lounick** [GitteV-2159432/ISfR#14]
The robot uses ROS2 to communicate with the Lidar/Wheels, so we need a lightweight ROS2 node that will translate from our messaging style to ROS2 and vice versa.

**Comment by GitteV-2159432** [comment]
https://docs.ros.org/en/humble/Tutorials.html

**Comment by GitteVandevenne** [comment]
Closed with: https://github.com/GitteV-2159432/ISfR/commit/239b7f6f56c0082906aa474d3cf78a1b89b2d4a2
